name: Update DEV.to posts in README

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch DEV.to posts
        run: |
          curl -s https://dev.to/api/articles?username=darthmoomancer \
            | jq -r '.[0:5] | .[] | "- [\(.title)](\(.url))"' > POSTS.md
      - name: Update README
        run: |
          # Replace everything between <!-- DEVTO-START --> and <!-- DEVTO-END -->
          awk '/<!-- DEVTO-START -->/{print; system("cat POSTS.md"); next} /<!-- DEVTO-END -->/{print; next} !/<!-- DEVTO-START -->|<!-- DEVTO-END -->/{print}' README.md > README.tmp
          mv README.tmp README.md
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update DEV.to posts" || echo "No changes"
          git push
