name: Update DEV.to posts in README

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:      # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo and allow push via GITHUB_TOKEN
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      # 2. Fetch latest 5 DEV.to posts
      - name: Fetch DEV.to posts
        run: |
          curl -s https://dev.to/api/articles?username=darthmoomancer \
            | jq -r '.[0:5] | .[] | "- [\(.title)](\(.url))"' > POSTS.md

      # 3. Replace section in README between <!-- DEVTO-START --> and <!-- DEVTO-END -->
      - name: Update README
        run: |
          awk '
          /<!-- DEVTO-START -->/ { print; system("cat POSTS.md"); next }
          /<!-- DEVTO-END -->/ { print; next }
          !/<!-- DEVTO-START -->|<!-- DEVTO-END -->/ { print }
          ' README.md > README.tmp
          mv README.tmp README.md

      # 4. Commit and push changes
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update DEV.to posts" || echo "No changes"
          git push
